export const CLICK_ON_BUTTOM = "CLICK_ON_BUTTOM"

// operator
export const SET_OPERATOR_INDEX_TO_STORE = "SET_OPERATOR_INDEX_TO_STORE";

// number

export const SET_NUMBER_TO_STORE = "SET_NUMBER_TO_STORE";

export const SET_THE_ANSWER_OF_QUESTION = "SET_THE_ANSWER_OF_QUESTION";


// wrong answer
export const CHOOSE_WRONG_ANSWER = "CHOOSE_WRONG_ANSWER"

export const CHOOSE_CORRECT_ANSWER = "CHOOSE_CORRECT_ANSWER"